// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyCongTrinhXayDung.Data;

#nullable disable

namespace QuanLyCongTrinhXayDung.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260511190750_UpdateBaoCaoTienDoV3")]
    partial class UpdateBaoCaoTienDoV3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.BaoCaoTienDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GiaiDoanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayBaoCao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ThanhVienId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TraLoi")
                        .HasColumnType("TEXT");

                    b.Property<int>("UuTien")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GiaiDoanId");

                    b.HasIndex("ThanhVienId");

                    b.ToTable("BaoCaoTienDos");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.ChamCong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("GioDen")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("GioVe")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("TEXT");

                    b.Property<int>("NhanCongId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SoCong")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("NhanCongId");

                    b.ToTable("ChamCongs");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.ChucVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChucVus");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.CongTrinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ChiPhiDuKien")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ChiPhiThucTe")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NguoiGiamSat")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("NguoiPhuTrach")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenCongTrinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ThoiGianHoanThanh")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrangThai")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CongTrinhs");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.DichVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("TEXT");

                    b.Property<int>("GiaiDoanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoaiDichVu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoaiDichVuKhac")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MucDichSuDung")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NhaCungCap")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<double>("SoLuong")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrangThai")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GiaiDoanId");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.GiaiDoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ChiPhiDuKien")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ChiPhiThucTe")
                        .HasColumnType("TEXT");

                    b.Property<int>("CongTrinhId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenGiaiDoan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ThoiGianHoanThanh")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrangThai")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CongTrinhId");

                    b.ToTable("GiaiDoans");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.HinhAnhBaoCao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaoCaoTienDoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaoCaoTienDoId");

                    b.ToTable("HinhAnhBaoCaos");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.MayMoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("TEXT");

                    b.Property<int>("GiaiDoanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenMay")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrangThai")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GiaiDoanId");

                    b.ToTable("MayMocs");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.NhanCong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChucVuId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GiaiDoanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Luong")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChucVuId");

                    b.HasIndex("GiaiDoanId");

                    b.ToTable("NhanCongs");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.ResetMatKhau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DaSuDung")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HanSuDung")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<int>("ThanhVienId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ThanhVienId");

                    b.ToTable("ResetMatKhaus");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.ThanhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChucVuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChucVuId");

                    b.ToTable("ThanhViens");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.VatLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("TEXT");

                    b.Property<int>("GiaiDoanId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SoLuong")
                        .HasColumnType("REAL");

                    b.Property<string>("TenVatLieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GiaiDoanId");

                    b.ToTable("VatLieus");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.BaoCaoTienDo", b =>
                {
                    b.HasOne("QuanLyCongTrinhXayDung.Models.GiaiDoan", "GiaiDoan")
                        .WithMany("BaoCaoTienDos")
                        .HasForeignKey("GiaiDoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyCongTrinhXayDung.Models.ThanhVien", "NguoiBaoCao")
                        .WithMany()
                        .HasForeignKey("ThanhVienId");

                    b.Navigation("GiaiDoan");

                    b.Navigation("NguoiBaoCao");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.ChamCong", b =>
                {
                    b.HasOne("QuanLyCongTrinhXayDung.Models.NhanCong", "NhanCong")
                        .WithMany("ChamCongs")
                        .HasForeignKey("NhanCongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanCong");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.DichVu", b =>
                {
                    b.HasOne("QuanLyCongTrinhXayDung.Models.GiaiDoan", "GiaiDoan")
                        .WithMany("DichVus")
                        .HasForeignKey("GiaiDoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaiDoan");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.GiaiDoan", b =>
                {
                    b.HasOne("QuanLyCongTrinhXayDung.Models.CongTrinh", "CongTrinh")
                        .WithMany("GiaiDoans")
                        .HasForeignKey("CongTrinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CongTrinh");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.HinhAnhBaoCao", b =>
                {
                    b.HasOne("QuanLyCongTrinhXayDung.Models.BaoCaoTienDo", "BaoCaoTienDo")
                        .WithMany("HinhAnhs")
                        .HasForeignKey("BaoCaoTienDoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaoCaoTienDo");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.MayMoc", b =>
                {
                    b.HasOne("QuanLyCongTrinhXayDung.Models.GiaiDoan", "GiaiDoan")
                        .WithMany("MayMocs")
                        .HasForeignKey("GiaiDoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaiDoan");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.NhanCong", b =>
                {
                    b.HasOne("QuanLyCongTrinhXayDung.Models.ChucVu", "ChucVu")
                        .WithMany("NhanCongs")
                        .HasForeignKey("ChucVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyCongTrinhXayDung.Models.GiaiDoan", "GiaiDoan")
                        .WithMany("NhanCongs")
                        .HasForeignKey("GiaiDoanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChucVu");

                    b.Navigation("GiaiDoan");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.ResetMatKhau", b =>
                {
                    b.HasOne("QuanLyCongTrinhXayDung.Models.ThanhVien", "ThanhVien")
                        .WithMany("ResetMatKhaus")
                        .HasForeignKey("ThanhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.ThanhVien", b =>
                {
                    b.HasOne("QuanLyCongTrinhXayDung.Models.ChucVu", "ChucVu")
                        .WithMany("ThanhViens")
                        .HasForeignKey("ChucVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.VatLieu", b =>
                {
                    b.HasOne("QuanLyCongTrinhXayDung.Models.GiaiDoan", "GiaiDoan")
                        .WithMany("VatLieus")
                        .HasForeignKey("GiaiDoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaiDoan");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.BaoCaoTienDo", b =>
                {
                    b.Navigation("HinhAnhs");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.ChucVu", b =>
                {
                    b.Navigation("NhanCongs");

                    b.Navigation("ThanhViens");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.CongTrinh", b =>
                {
                    b.Navigation("GiaiDoans");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.GiaiDoan", b =>
                {
                    b.Navigation("BaoCaoTienDos");

                    b.Navigation("DichVus");

                    b.Navigation("MayMocs");

                    b.Navigation("NhanCongs");

                    b.Navigation("VatLieus");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.NhanCong", b =>
                {
                    b.Navigation("ChamCongs");
                });

            modelBuilder.Entity("QuanLyCongTrinhXayDung.Models.ThanhVien", b =>
                {
                    b.Navigation("ResetMatKhaus");
                });
#pragma warning restore 612, 618
        }
    }
}
